/***********************************
*
* error.h   Codigos de error
*
**********************************/

#ifndef error_h
#define error_h

#define MAX_SYNTAX_ERRORS 25

typedef enum {
	NO_ERROR, //
	SYNTAX_ERROR, //
	TOO_MANY_SYNTAX_ERRORS, //
	FAILED_SOURCE_FILE_OPEN, //
	UNEXPECTED_END_OF_FILE, // 
	INVALID_NUMBER, //
	INVALID_FRACTION, //
	INVALID_EXPONENT, //
	TOO_MANY_DIGITS, //
	REAL_OUT_OF_RANGE, //
	INTEGER_OUT_OF_RANGE, //
	MISSING_LPAREN, //
	MISSING_RPAREN, //
	INVALID_EXPRESSION, //
	INVALID_ASIGNMENT, //
	MISSING_IDENTIFIER, // 
	INVALID_WEND, //
	MISSING_WEND, //	
	UNDEFINED_IDENTIFIER, //
	STACK_OVERFLOW,
	INVALID_STATEMENT, //
	UNEXPECTED_TOKEN, // 
	MISSING_SEMICOLON,
	INVALID_GOSUB, //
	INVALID_IFEND, //
	MISSING_IFEND, //
	INVALID_ELSE, //
	INVALID_THEN, //
	INVALID_FOR_CONTROL, //
	MISSING_CONSTANT,//
	MISSING_COLON, //
	MISSING_END, //
	MISSING_TO, //
	REDEFINED_IDENTIFIER,
	MISSING_EQUAL,//
	INVALID_NEXT, //
	NEXT_SIN_FOR, //
	INVALID_SUBRANGE_TYPE,
	MISSING_CASE, //
	MISSING_CEND, //
	INVALID_CASE, //
	INVALID_CEND, //
	INVALID_OTHERWISE, //
	MISSING_COMMA, //
	ERRONEOUS_MX_TYPE, //
	INVALID_TARGETS,
	INVALID_IDENTIFIER, //
	INCOMPATIBLE_ASSIGNMENT,
	MIN_GT_MAX,
	MAT_MIS_LPAREN,
	MISSING_RBRACKET, //
	INVALID_INDEX_TYPE, //
	SENTENCE_OUT_OF_EXECUTION, // MIA
	MISSING_PERIOD,
	TOO_MANY_SUBSCRIPTS,
	INVALID_COMPARATION, // MIA
	NESTING_TOO_DEEP,
	MISSING_PROGRAM,
	INVALID_STRING_EXP, //
	INVALID_FLOAT_EXP, //
	INVALID_INT_EXP, //
	INVALID_NUMBER_EXP, //
	WRONG_NUMBER_OF_PARMS,
	INVALID_VAR_PARM,
	WRONG_CASE_TYPE, //
	MISSING_STRING, //
	INVALID_LABEL, // MIA.
	UNIMPLEMENTED_FEATURE, //
	UNCLOSED_WHILE, //
	UNCLOSED_FOR, //
	UNCLOSED_THEN, //
	UNCLOSED_SELECT, //
	UNCLOSED_UNKNOWN,
	WRONG_OPTION_CASE, //
	ONLY_VALID_AT_START, //
} ERROR_CODE;

#endif

